# Generated by Django 2.1.5 on 2019-03-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_link_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='descriptions',
            new_name='description',
        ),
    ]
